// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3FY5qUh6aIM6ludpL3s9tZNFSBCxXcuk',
    appId: '1:202382514585:web:04d89a80ad8149ae24db08',
    messagingSenderId: '202382514585',
    projectId: 'tinytask-99a5f',
    authDomain: 'tinytask-99a5f.firebaseapp.com',
    databaseURL: 'https://tinytask-99a5f-default-rtdb.firebaseio.com',
    storageBucket: 'tinytask-99a5f.appspot.com',
    measurementId: 'G-D81R208706',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtcrqZDhKdFgPJCJzmhWIA-Ei9oBEHqQQ',
    appId: '1:202382514585:android:882ade15a361502f24db08',
    messagingSenderId: '202382514585',
    projectId: 'tinytask-99a5f',
    databaseURL: 'https://tinytask-99a5f-default-rtdb.firebaseio.com',
    storageBucket: 'tinytask-99a5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFvaePxaRdZmKrGsDhoB3NyVySnvVs6mA',
    appId: '1:202382514585:ios:526aa9d5d471091f24db08',
    messagingSenderId: '202382514585',
    projectId: 'tinytask-99a5f',
    databaseURL: 'https://tinytask-99a5f-default-rtdb.firebaseio.com',
    storageBucket: 'tinytask-99a5f.appspot.com',
    iosBundleId: 'com.example.tinytaskapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFvaePxaRdZmKrGsDhoB3NyVySnvVs6mA',
    appId: '1:202382514585:ios:94a7c6f6ee4d301124db08',
    messagingSenderId: '202382514585',
    projectId: 'tinytask-99a5f',
    databaseURL: 'https://tinytask-99a5f-default-rtdb.firebaseio.com',
    storageBucket: 'tinytask-99a5f.appspot.com',
    iosBundleId: 'com.example.tinytaskapp.RunnerTests',
  );
}
